# Generated by Django 5.2.6 on 2026-02-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproduct_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adderss_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adderss_line_2',
            new_name='address_line_2',
        ),
    ]
